filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/*
  scan_frequency: 1s
  encoding: plain
  

output.logstash:
  hosts: ["127.0.0.1:5044"]

path.data: /tmp/filebeat
path.logs: /tmp/filebeat/logs
